// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://ntr3kg5gtjavrgyaqcff6lgk4u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ayhbrpepfzda5ecrsliv6gb7dm",
    "aws_cognito_identity_pool_id": "us-east-2:dd6fc4ac-b1e8-4c71-ad24-a33bbf73ea97",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_qiGYsKW0r",
    "aws_user_pools_web_client_id": "63hcc7erfe1qt4eh1bsm00mnbb",
    "oauth": {},
    "aws_user_files_s3_bucket": "genshinplannera2c57fdbc5164a6b8f94392805cd599f155138-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
